/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.atm;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        int balance = 1000;
        int withdraw = 0;
        int deposit = 0;
        Scanner sc = new Scanner(System.in);

        while(true) {
            System.out.println("ATM");
            System.out.println("Choose 1 for Withdraw");
            System.out.println("Choose 2 for Deposit");
            System.out.println("Choose 3 for Check Balance");
            System.out.println("Choose 4 for EXIT");

            int choice = sc.nextInt();
            switch(choice){
                case 1:
                    System.out.println("Enter money to be withdrawn");
                    withdraw = sc.nextInt();

                    if(balance >= withdraw){
                        balance = balance - withdraw;
                        System.out.println("Please collect your money");
                    }
                    else {
                        System.out.println("Transaction was not possible");
                    }
                    System.out.println("");
                    break;
            
                case 2:
                    System.out.println("Enter money to be deposited");
                    deposit = sc.nextInt();

                    balance = balance + deposit;
                    System.out.println("Your money has been succesfully deposited");
                    System.out.println("");
                    break;
                
                    case 3:
                        System.out.println("Balance: "+balance);
                        System.out.println("");
                        break;
                    case 4:
                    System.exit(0);
            }

        }
    }
}
