/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.fp.textinput;

import javafx.application.Application;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.TextField;
import javafx.scene.layout.BorderPane;
import javafx.scene.layout.FlowPane;
import javafx.stage.Stage;

public class TextFrequencyStoreUI extends Application{
    
    private TextFrequencyStore logic;
    private TextField textInput;
    private Button save;
    
    @Override
    public void init() throws Exception{
        textInput = new TextField();
        textInput.setPrefColumnCount(20);
        save = new Button("Save");
        save.setOnAction(
            e -> {
                logic.addTextInput(textInput);
                textInput.clear();
            }
        );
    }
    
    private Parent createSceneGraph(){
        FlowPane top = new FlowPane();
        top.getChildren().addAll(textInput);
        FlowPane bottom = new FlowPane();
        bottom.getChildren().addAll(save);
        BorderPane borderPane = new BorderPane();
        borderPane.setBottom(save);
        borderPane.setTop(top);

        return borderPane;
    } 

    @Override
    public void start(Stage primaryStage) throws Exception {
        
        primaryStage.setTitle("My Application");
        Scene scene = new Scene(createSceneGraph(), 600, 600);
        primaryStage.setScene(scene);
        primaryStage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }

    
}
