/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.fp.cards;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class App {

    public String getGreeting() {
        return "Hello World!";
    }

    public static void checkIfEnoughCards(String[] arr)throws IllegalStateException{
        int players = Integer.parseInt(arr[0]);
        int cards = Integer.parseInt(arr[1]);
        
        if(cards * players > 52){
            throw new IllegalStateException("The player card composition cannot be succeded.");
        }
    }

    public static void main(String[] args) {
        checkIfEnoughCards(args);
        List<String> stack = new ArrayList<String>();
        
        stack.add("Herz 1");
        stack.add("Herz 2");
        stack.add("Herz 3");
        stack.add("Herz 4");
        stack.add("Herz 5");
        stack.add("Herz 6");
        stack.add("Herz 7");
        stack.add("Herz 8");
        stack.add("Herz 9");
        stack.add("Herz Bube");
        stack.add("Herz Dame");
        stack.add("Herz König");
        stack.add("Herz Ass");

        stack.add("Kreuz 1");
        stack.add("Kreuz 2");
        stack.add("Kreuz 3");
        stack.add("Kreuz 4");
        stack.add("Kreuz 5");
        stack.add("Kreuz 6");
        stack.add("Kreuz 7");
        stack.add("Kreuz 8");
        stack.add("Kreuz 9");
        stack.add("Kreuz Bube");
        stack.add("Kreuz Dame");
        stack.add("Kreuz König");
        stack.add("Kreuz Ass");

        stack.add("Pik 1");
        stack.add("Pik 2");
        stack.add("Pik 3");
        stack.add("Pik 4");
        stack.add("Pik 5");
        stack.add("Pik 6");
        stack.add("Pik 7");
        stack.add("Pik 8");
        stack.add("Pik 9");
        stack.add("Pik Bube");
        stack.add("Pik Dame");
        stack.add("Pik König");
        stack.add("Pik Ass");

        stack.add("Karo 1");
        stack.add("Karo 2");
        stack.add("Karo 3");
        stack.add("Karo 4");
        stack.add("Karo 5");
        stack.add("Karo 6");
        stack.add("Karo 7");
        stack.add("Karo 8");
        stack.add("Karo 9");
        stack.add("Karo Bube");
        stack.add("Karo Dame");
        stack.add("Karo König");
        stack.add("Karo Ass");

        Collections.shuffle(stack);

        int useCards = Integer.parseInt(args[0]) * Integer.parseInt(args[1]);

        System.out.println("This is the starting deck: " + stack);

        for(int i = 0; i < useCards; i += Integer.parseInt(args[1])){
            System.out.println("Player deck: " + stack.subList(i, i + Integer.parseInt(args[1])));    
            stack.subList(i, i + Integer.parseInt(args[1])).clear();
        }
        System.out.println("This is the remaining deck: " + stack);
       
    }
}
