/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.fp.wohnheime;

import java.util.ArrayList;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
        Student jeff = new Student("Jeff", "WI");
        Student manu = new Student("Manu", "DMM");
        Student ole = new Student("Ole", "physics");
        Student amrit = new Student("amrit", "jura");
        Student adrian = new Student("adrian", "sportmanagement");

        SharedFlat wg1 = new SharedFlat(2);
        wg1.addStudent(jeff);
        wg1.addStudent(ole);
        wg1.addStudent(adrian);


        SharedFlat wg2 = new SharedFlat(3);
        wg2.addStudent(manu);
        wg2.addStudent(amrit);

        ArrayList<SharedFlat> flats = new ArrayList<SharedFlat>();
        flats.add(wg1);
        flats.add(wg2);

        Dormitory wohnheim = new Dormitory(flats);
        
        //System.out.println(wohnheim.amountOfRentingStudents());
        //System.out.println(wohnheim.getNamesOfStudemts());
        System.out.println(wohnheim.getStudentsName());
        System.out.println(wg1.amountOfStudents());
    }
}
