/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.fp.campus;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
        Faculty inf = new Faculty("INF");
        Professor martin = new Professor("martin", 45, inf);
        martin.setResearchArea("Java");

        Assistant kevin = new Assistant("Kevin", 27, inf);
        kevin.setBoss(martin);
        Assistant jürgen = new Assistant("jürgen", 24, inf);
        jürgen.setBoss(martin);

        inf.addProfessor(martin);
        inf.addAssistant(kevin);
        inf.addAssistant(jürgen);

        System.out.println(martin);
        System.out.println(kevin);
        System.out.println(inf);
        System.out.println(inf.getAssistantsOfProfessor(martin));
        System.out.println(inf.getProfessorWithAssistant());
        System.out.println(inf.getAmountAssis());
    }
}
