/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.fp.nextday;

public class App {
    

    public static void main(String[] args) {
        Date datum = new Date(20, Month.APRIL, 2021);
        Date datum1 = new Date(28, Month.FEBRUARY, 2019);
        Date datum2 = new Date(29, Month.FEBRUARY, 2020);

        System.out.println(datum.setNextDay());
        System.out.println(datum1.setNextDay());
        System.out.println(datum2.setNextDay());
    }
}
