/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.fp.tacker;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        //init
        int anzahlSeiten = 5;
        int anzahlKlammern = 10;
        int kapazitaetTacker = 10;
        Tacker myTacker = new Tacker(kapazitaetTacker);

        //Happy Path
        myTacker.ladeTacker(anzahlKlammern);
        myTacker.tackerSeiten(5);
        
        //Ausnahme: Zu viele Seiten
        anzahlSeiten=20;
        myTacker.tackerSeiten(anzahlSeiten);

        //Ausnahme: Magazin wird geleert!
        anzahlSeiten=5;
        for (int i = 0; i < anzahlKlammern; i++)
            myTacker.tackerSeiten(anzahlSeiten);
    }
}
