/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.fp.counter.view;


import io.fp.counter.model.CounterModel;
import javafx.application.Application;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.stage.Stage;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.layout.BorderPane;

public class CounterView extends Application{

    private CounterModel model;
    
    private Button clickMe;
    private Label numberOfClicks;
    private Parent root;
    private final static String PREFIX ="Number of Clicks: ";

    @Override
    public void init() throws Exception{
        model = new CounterModel();
        clickMe = new Button("Click Me!");
        clickMe.setOnAction( 
            e ->{
                model.increaseCounter();
                updateNumberOfClicks(model.getCounter());
            }
        );
        numberOfClicks = new Label(PREFIX+0);
        root = createSceneGraph();
    }

    public Parent createSceneGraph(){
        BorderPane root = new BorderPane();
        root.setCenter(clickMe);
        root.setBottom(numberOfClicks);
        return root;
    }
    @Override
    public void stop() throws Exception{
        
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        primaryStage.setTitle("Click to Count");
        Scene scene = new Scene(root, 400, 400);
        primaryStage.setScene(scene);
        primaryStage.show();
    
    }

    public void updateNumberOfClicks(int number) {
        numberOfClicks.setText(PREFIX+number);
    }

    public static void main(String[] args) {
        launch(args);
    }
}
